# Generated by Django 4.2.20 on 2025-11-01 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('customer_type', models.CharField(choices=[('private', 'Privatperson'), ('business', 'Gewerbe')], default='private', max_length=20)),
                ('address', models.TextField()),
                ('consent_timestamp', models.DateTimeField()),
                ('consent_ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('building_type', models.CharField(choices=[('efh', 'Einfamilienhaus'), ('mfh', 'Mehrfamilienhaus'), ('commercial', 'Gewerbe')], max_length=50)),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('main_fuse_ampere', models.PositiveIntegerField(help_text='Hauptsicherung in Ampere')),
                ('grid_type', models.CharField(choices=[('TN-C', 'TN-C'), ('TN-S', 'TN-S'), ('TT', 'TT')], max_length=10)),
                ('distance_meter_to_hak', models.DecimalField(decimal_places=2, help_text='Entfernung Zählerschrank zu HAK in Metern', max_digits=5)),
                ('meter_cabinet_photo', models.ImageField(blank=True, null=True, upload_to='uploads/meter_cabinets/')),
                ('hak_photo', models.ImageField(blank=True, null=True, upload_to='uploads/hak/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
