# Generated by Django 4.2.26 on 2025-11-09 10:30

from django.db import migrations, models


def forward_convert_grid_types(apps, schema_editor):
    Site = apps.get_model('customers', 'Site')
    mapping = {
        'TN-C': '3p',
        'TN-S': '3p',
        'TT': '1p',
        '3p': '3p',
        '1p': '1p',
        'unknown': 'unknown',
        '': 'unknown',
        None: 'unknown',
    }
    for site in Site.objects.all():
        new_value = mapping.get(site.grid_type, 'unknown')
        if site.grid_type != new_value:
            site.grid_type = new_value
            site.save(update_fields=['grid_type'])


def backward_convert_grid_types(apps, schema_editor):
    Site = apps.get_model('customers', 'Site')
    reverse_mapping = {
        '1p': 'TT',
        '3p': 'TN-S',
        'unknown': 'TN-S',
        None: 'TN-S',
        '': 'TN-S',
    }
    for site in Site.objects.all():
        new_value = reverse_mapping.get(site.grid_type, 'TN-S')
        if site.grid_type != new_value:
            site.grid_type = new_value
            site.save(update_fields=['grid_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_last_quote_number_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_convert_grid_types, backward_convert_grid_types),
        migrations.AlterField(
            model_name='site',
            name='grid_type',
            field=models.CharField(blank=True, choices=[('1p', '1-Polig'), ('3p', '3-Polig'), ('unknown', 'Unbekannt')], default='unknown', max_length=10),
        ),
    ]
