# Generated by Django 4.2.26 on 2025-11-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_site_grid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='grid_type',
            field=models.CharField(blank=True, choices=[('1p', '1-Polig'), ('3p', '3-Polig'), ('unknown', 'Unbekannt')], max_length=10),
        ),
    ]
