# Generated by Django 4.2.26 on 2025-11-12 03:50

import apps.quotes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_site_grid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='hak_photo',
            field=models.FileField(blank=True, help_text='Datei Hausanschlusskasten (JPG, PNG oder PDF, max 5MB)', null=True, upload_to='uploads/hak/', validators=[apps.quotes.validators.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='site',
            name='meter_cabinet_photo',
            field=models.FileField(blank=True, help_text='Datei Zählerschrank (JPG, PNG oder PDF, max 5MB)', null=True, upload_to='uploads/meter_cabinets/', validators=[apps.quotes.validators.validate_media_file]),
        ),
    ]
