# Generated by Django 4.2.26 on 2025-11-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_site_hak_photo_alter_site_meter_cabinet_photo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customer_email_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', '-created_at'], name='customer_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['customer', '-created_at'], name='site_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['building_type'], name='site_building_idx'),
        ),
    ]
