# Generated by Django 4.2.26 on 2025-11-17 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0024_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='Art des Events (z.B. precheck_submitted, quote_approved)', max_length=50)),
                ('direction', models.CharField(choices=[('outgoing', 'Django → N8n'), ('incoming', 'N8n → Django')], default='outgoing', help_text='Richtung des Webhook-Calls', max_length=10)),
                ('payload', models.JSONField(help_text='Gesendete/Empfangene Daten als JSON')),
                ('response', models.JSONField(blank=True, help_text='Antwort vom Empfänger', null=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('success', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('retry', 'Wird wiederholt')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Fehlermeldung falls status=failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Anzahl der Wiederholungsversuche')),
                ('precheck_id', models.IntegerField(blank=True, db_index=True, help_text='Zugehöriger Precheck (falls relevant)', null=True)),
                ('quote_id', models.IntegerField(blank=True, db_index=True, help_text='Zugehöriges Quote (falls relevant)', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='integration_created_cab9e3_idx'), models.Index(fields=['event_type', 'status'], name='integration_event_t_922043_idx')],
            },
        ),
        migrations.CreateModel(
            name='N8nWorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(blank=True, help_text='N8n Workflow Execution ID', max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Workflow gestartet'), ('data_validation', 'Daten werden validiert'), ('incomplete', 'Daten unvollständig'), ('waiting_customer', 'Wartet auf Kundenantwort'), ('generating_quote', 'Angebot wird erstellt'), ('quote_ready', 'Angebot fertig'), ('sent_to_customer', 'An Kunde versendet'), ('failed', 'Fehler aufgetreten')], db_index=True, default='initiated', max_length=50)),
                ('ai_validation_result', models.JSONField(blank=True, help_text='Ergebnis der KI-Validierung (complete, missing_data, etc.)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Zusätzliche Workflow-Informationen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('precheck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='quotes.precheck')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'N8n Workflow Status',
                'verbose_name_plural': 'N8n Workflow Status',
                'ordering': ['-created_at'],
            },
        ),
    ]
