# Generated by Django 4.2.26 on 2025-11-18 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True, help_text='N8n Webhook URL (wohin Django Webhooks sendet)', max_length=500)),
                ('api_key', models.CharField(blank=True, help_text='API-Key für N8n-Authentifizierung (optional)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='N8n Integration aktiviert')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'N8n Konfiguration',
                'verbose_name_plural': 'N8n Konfiguration',
            },
        ),
    ]
