# Generated by Django 4.2.20 on 2025-11-01 06:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('inverter', 'Wechselrichter'), ('battery', 'Speicher'), ('spd', 'Überspannungsschutz'), ('meter', 'Zählerplatz'), ('cable', 'Kabel'), ('switch', 'Schalter'), ('other', 'Sonstiges')], max_length=20)),
                ('vendor', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('datasheet_url', models.URLField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compatible_with', models.ManyToManyField(blank=True, to='quotes.component')),
            ],
            options={
                'ordering': ['type', 'vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Precheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_power_kw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inverter_class', models.CharField(choices=[('1kva', 'bis 1 kVA'), ('3kva', 'bis 3 kVA'), ('5kva', 'bis 5 kVA'), ('10kva', 'bis 10 kVA')], max_length=10)),
                ('storage_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('own_components', models.BooleanField(default=False, help_text='Kunde bringt eigene Komponenten mit')),
                ('component_files', models.TextField(default='[]', help_text='JSON Liste der hochgeladenen Komponentendatenblätter')),
                ('preferred_timeframes', models.TextField(default='[]', help_text='JSON Gewünschte Zeitfenster')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'In Prüfung'), ('approved', 'Freigegeben'), ('sent', 'Versendet'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt'), ('expired', 'Abgelaufen')], default='draft', max_length=20)),
                ('pdf_url', models.URLField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('precheck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotes.precheck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.component')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
