# Generated by Django 4.2.20 on 2025-11-03 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('travel_zone_0', 'Anfahrt Zone 0 (Hamburg)'), ('travel_zone_30', 'Anfahrt Zone 30 (bis 30km)'), ('travel_zone_60', 'Anfahrt Zone 60 (bis 60km)'), ('surcharge_tt_grid', 'TT-Netz Zuschlag'), ('surcharge_selective_fuse', 'Selektive Vorsicherung'), ('surcharge_cable_meter', 'Kabel pro Meter (über 15m)'), ('discount_complete_kit', 'Komplett-Kit Rabatt %'), ('package_basis', 'Basis-Paket'), ('package_plus', 'Plus-Paket'), ('package_pro', 'Pro-Paket'), ('material_ac_wiring', 'AC-Verkabelung'), ('material_spd', 'Überspannungsschutz'), ('material_meter_upgrade', 'Zählerplatz-Ertüchtigung'), ('material_storage_kwh', 'Speicher pro kWh')], max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_percentage', models.BooleanField(default=False, help_text='Ist der Wert ein Prozentsatz?')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preiskonfiguration',
                'verbose_name_plural': 'Preiskonfigurationen',
                'ordering': ['price_type'],
            },
        ),
    ]
