# Generated by Django 4.2.26 on 2025-11-09 03:41

import apps.quotes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_seed_wallbox_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='precheck',
            name='cable_route_photo',
            field=models.ImageField(blank=True, help_text='Foto Kabelwege (JPG/PNG, max 5MB)', null=True, upload_to='precheck/cables/%Y/%m/', validators=[apps.quotes.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='precheck',
            name='hak_photo',
            field=models.ImageField(blank=True, help_text='Foto Hausanschlusskasten (JPG/PNG, max 5MB)', null=True, upload_to='precheck/hak/%Y/%m/', validators=[apps.quotes.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='precheck',
            name='location_photo',
            field=models.ImageField(blank=True, help_text='Foto Montageorte (JPG/PNG, max 5MB)', null=True, upload_to='precheck/locations/%Y/%m/', validators=[apps.quotes.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='precheck',
            name='meter_cabinet_photo',
            field=models.ImageField(blank=True, help_text='Foto Zählerschrank (JPG/PNG, max 5MB)', null=True, upload_to='precheck/meter_cabinet/%Y/%m/', validators=[apps.quotes.validators.validate_image_file]),
        ),
    ]
