# Generated by Django 4.2.26 on 2025-11-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_precheck_cable_route_photo_precheck_hak_photo_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='precheck',
                    name='wallbox',
                    field=models.BooleanField(default=False, help_text='Kunde wünscht eine Wallbox'),
                ),
                migrations.AddField(
                    model_name='precheck',
                    name='wallbox_cable_length_m',
                    field=models.DecimalField(blank=True, decimal_places=2, help_text='Länge der Wallbox-Zuleitung in Metern', max_digits=6, null=True),
                ),
                migrations.AddField(
                    model_name='precheck',
                    name='wallbox_cable_prepared',
                    field=models.BooleanField(default=False, help_text='Ist die Zuleitung bereits vorbereitet?'),
                ),
                migrations.AddField(
                    model_name='precheck',
                    name='wallbox_class',
                    field=models.CharField(blank=True, choices=[('4kw', 'Wallbox bis 4 kW'), ('11kw', 'Wallbox 11 kW'), ('22kw', 'Wallbox 22 kW')], default='', help_text='Gewünschte Wallbox-Leistungsklasse', max_length=4),
                ),
                migrations.AddField(
                    model_name='precheck',
                    name='wallbox_mount',
                    field=models.CharField(blank=True, choices=[('wall', 'Wandmontage'), ('stand', 'Ständermontage')], default='', help_text='Montageart der Wallbox', max_length=10),
                ),
            ],
        ),
    ]
