# Generated by Django 4.2.26 on 2025-11-10 16:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_remove_precheck_inverter_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Kategoriename')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sortierreihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Produktkategorie',
                'verbose_name_plural': 'Produktkategorien',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('unit', models.CharField(choices=[('piece', 'Stück'), ('meter', 'Meter'), ('hour', 'Stunde'), ('kwh', 'kWh'), ('kwp', 'kWp'), ('set', 'Set'), ('package', 'Paket'), ('lump_sum', 'Pauschal')], default='piece', max_length=20, verbose_name='Einheit')),
                ('purchase_price_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Einkaufspreis (netto)')),
                ('sales_price_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Verkaufspreis (netto)')),
                ('vat_rate', models.DecimalField(choices=[(Decimal('0.00'), '0% (Steuerfrei)'), (Decimal('0.07'), '7% (Ermäßigt)'), (Decimal('0.19'), '19% (Standard)')], decimal_places=2, default=Decimal('0.19'), max_digits=4, verbose_name='MwSt.-Satz')),
                ('stock_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Lagerbestand')),
                ('min_stock_level', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mindestbestand')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hervorgehoben')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Lieferant')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='quotes.productcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
                'ordering': ['category__sort_order', 'category__name', 'name'],
            },
        ),
    ]
