# Generated by Django 4.2.26 on 2025-11-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_productcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Stück'), ('meter', 'Meter'), ('hour', 'Stunde'), ('kwh', 'kWh'), ('kwp', 'kWp'), ('set', 'Set'), ('package', 'Paket'), ('lump_sum', 'Pauschal'), ('percent', 'Prozent')], default='piece', max_length=20, verbose_name='Einheit'),
        ),
    ]
