# Generated by Django 4.2.26 on 2025-11-10 17:42

from decimal import Decimal

from django.db import migrations


def seed_precheck_catalog(apps, schema_editor):
    ProductCategory = apps.get_model('quotes', 'ProductCategory')
    Product = apps.get_model('quotes', 'Product')
    PriceConfig = apps.get_model('quotes', 'PriceConfig')

    category, _ = ProductCategory.objects.get_or_create(
        name='Precheck',
        defaults={
            'description': 'Preisbausteine f\u00fcr den Precheck-Rechner',
            'sort_order': 50,
            'is_active': True,
        },
    )

    items = [
        # Pakete
        {
            'price_type': 'package_basis',
            'name': 'Precheck Paket Basis',
            'description': 'Basis-Paket (bis 3 kVA, AC-Anschluss, MaStR/Netzmeldung)',
            'unit': 'package',
            'default_value': Decimal('890.00'),
        },
        {
            'price_type': 'package_plus',
            'name': 'Precheck Paket Plus',
            'description': 'Plus-Paket (inkl. Z\u00e4hlerplatz-Ert\u00fcchtigung & SPD)',
            'unit': 'package',
            'default_value': Decimal('1490.00'),
        },
        {
            'price_type': 'package_pro',
            'name': 'Precheck Paket Pro',
            'description': 'Pro-Paket (inkl. Speicherintegration & Energiemanagement)',
            'unit': 'package',
            'default_value': Decimal('2290.00'),
        },
        # Anfahrt
        {
            'price_type': 'travel_zone_0',
            'name': 'Anfahrtszone 0 (Hamburg)',
            'description': 'Anfahrt innerhalb Hamburg',
            'unit': 'lump_sum',
            'default_value': Decimal('0.00'),
        },
        {
            'price_type': 'travel_zone_30',
            'name': 'Anfahrtszone 30 km',
            'description': 'Anfahrt bis 30 km um Hamburg',
            'unit': 'lump_sum',
            'default_value': Decimal('50.00'),
        },
        {
            'price_type': 'travel_zone_60',
            'name': 'Anfahrtszone 60 km',
            'description': 'Anfahrt bis 60 km um Hamburg',
            'unit': 'lump_sum',
            'default_value': Decimal('95.00'),
        },
        # Zuschl\u00e4ge & Material
        {
            'price_type': 'surcharge_tt_grid',
            'name': 'TT-Netz Zuschlag',
            'description': 'Zusatzaufwand f\u00fcr TT-Netze',
            'unit': 'lump_sum',
            'default_value': Decimal('150.00'),
        },
        {
            'price_type': 'surcharge_selective_fuse',
            'name': 'Selektive Vorsicherung',
            'description': 'Mehrkosten f\u00fcr selektive Vorsicherung',
            'unit': 'lump_sum',
            'default_value': Decimal('220.00'),
        },
        {
            'price_type': 'material_ac_wiring',
            'name': 'AC-Verkabelung',
            'description': 'Material & Montage AC-Verkabelung',
            'unit': 'lump_sum',
            'default_value': Decimal('180.00'),
        },
        {
            'price_type': 'material_spd',
            'name': '\u00dcberspannungsschutz (SPD)',
            'description': 'Material & Einbau SPD',
            'unit': 'lump_sum',
            'default_value': Decimal('320.00'),
        },
        {
            'price_type': 'material_meter_upgrade',
            'name': 'Z\u00e4hlerplatz-Ert\u00fcchtigung',
            'description': 'Material & Montage Z\u00e4hlerplatz',
            'unit': 'lump_sum',
            'default_value': Decimal('450.00'),
        },
        {
            'price_type': 'material_storage_kwh',
            'name': 'Speicherintegration pro kWh',
            'description': 'Montage & Material f\u00fcr Speicher je kWh',
            'unit': 'kwh',
            'default_value': Decimal('800.00'),
        },
        # Wallbox Basiskosten
        {
            'price_type': 'wallbox_base_4kw',
            'name': 'Wallbox Installation bis 4 kW',
            'description': 'Installation Wallbox bis 4 kW',
            'unit': 'lump_sum',
            'default_value': Decimal('890.00'),
        },
        {
            'price_type': 'wallbox_base_11kw',
            'name': 'Wallbox Installation 11 kW',
            'description': 'Installation Wallbox 11 kW',
            'unit': 'lump_sum',
            'default_value': Decimal('1290.00'),
        },
        {
            'price_type': 'wallbox_base_22kw',
            'name': 'Wallbox Installation 22 kW',
            'description': 'Installation Wallbox 22 kW',
            'unit': 'lump_sum',
            'default_value': Decimal('1690.00'),
        },
        {
            'price_type': 'wallbox_stand_mount',
            'name': 'Wallbox St\u00e4nder-Montage',
            'description': 'Zuschlag f\u00fcr St\u00e4nder-Montage',
            'unit': 'lump_sum',
            'default_value': Decimal('350.00'),
        },
        {
            'price_type': 'wallbox_pv_surplus',
            'name': 'PV-\u00dcberschussladen',
            'description': 'Konfiguration PV-\u00dcberschussladen',
            'unit': 'lump_sum',
            'default_value': Decimal('0.00'),
        },
        # Verkabelung WR
        {
            'price_type': 'cable_wr_up_to_5kw',
            'name': 'Wechselrichter-Kabel bis 5 kW',
            'description': 'Pro Meter WR-Kabel (bis 5 kW)',
            'unit': 'meter',
            'default_value': Decimal('15.00'),
        },
        {
            'price_type': 'cable_wr_5_to_10kw',
            'name': 'Wechselrichter-Kabel 5-10 kW',
            'description': 'Pro Meter WR-Kabel (5-10 kW)',
            'unit': 'meter',
            'default_value': Decimal('25.00'),
        },
        {
            'price_type': 'cable_wr_above_10kw',
            'name': 'Wechselrichter-Kabel \u00fcber 10 kW',
            'description': 'Pro Meter WR-Kabel (>10 kW)',
            'unit': 'meter',
            'default_value': Decimal('35.00'),
        },
        # Verkabelung Wallbox
        {
            'price_type': 'cable_wb_4kw',
            'name': 'Wallbox-Kabel bis 4 kW',
            'description': 'Pro Meter Wallbox-Kabel (<4 kW)',
            'unit': 'meter',
            'default_value': Decimal('12.00'),
        },
        {
            'price_type': 'cable_wb_11kw',
            'name': 'Wallbox-Kabel 11 kW',
            'description': 'Pro Meter Wallbox-Kabel (11 kW)',
            'unit': 'meter',
            'default_value': Decimal('20.00'),
        },
        {
            'price_type': 'cable_wb_22kw',
            'name': 'Wallbox-Kabel 22 kW',
            'description': 'Pro Meter Wallbox-Kabel (22 kW)',
            'unit': 'meter',
            'default_value': Decimal('30.00'),
        },
        # Rabatt
        {
            'price_type': 'discount_complete_kit',
            'name': 'Rabatt Komplett-Kit',
            'description': 'Rabatt bei Komplettlieferung (in % oder Euro)',
            'unit': 'lump_sum',
            'default_value': Decimal('15.00'),
            'supports_percentage': True,
        },
    ]

    for item in items:
        price_type = item['price_type']
        sku = f"PCHK-{price_type.upper().replace('_', '-')}"
        value = item['default_value']
        unit = item['unit']
        is_percentage = item.get('supports_percentage', False)

        try:
            config = PriceConfig.objects.get(price_type=price_type)
            value = config.value
            # \u00dcbernehme Prozent-Flag nur, wenn das Item dies zul\u00e4sst
            if item.get('supports_percentage'):
                is_percentage = config.is_percentage
            else:
                is_percentage = False
        except PriceConfig.DoesNotExist:
            pass

        Product.objects.update_or_create(
            sku=sku,
            defaults={
                'category': category,
                'name': item['name'],
                'description': item['description'],
                'unit': 'percent' if is_percentage else unit,
                'purchase_price_net': Decimal('0.00'),
                'sales_price_net': value,
                'vat_rate': Decimal('0.19'),
                'notes': f"Precheck Preisbaustein ({price_type})",
                'is_active': True,
                'is_featured': False,
            },
        )


def remove_precheck_catalog(apps, schema_editor):
    Product = apps.get_model('quotes', 'Product')
    ProductCategory = apps.get_model('quotes', 'ProductCategory')

    price_types = [
        'package_basis',
        'package_plus',
        'package_pro',
        'travel_zone_0',
        'travel_zone_30',
        'travel_zone_60',
        'surcharge_tt_grid',
        'surcharge_selective_fuse',
        'material_ac_wiring',
        'material_spd',
        'material_meter_upgrade',
        'material_storage_kwh',
        'wallbox_base_4kw',
        'wallbox_base_11kw',
        'wallbox_base_22kw',
        'wallbox_stand_mount',
        'wallbox_pv_surplus',
        'cable_wr_up_to_5kw',
        'cable_wr_5_to_10kw',
        'cable_wr_above_10kw',
        'cable_wb_4kw',
        'cable_wb_11kw',
        'cable_wb_22kw',
        'discount_complete_kit',
    ]

    skus = [f"PCHK-{pt.upper().replace('_', '-')}" for pt in price_types]
    Product.objects.filter(sku__in=skus).delete()

    try:
        category = ProductCategory.objects.get(name='Precheck')
    except ProductCategory.DoesNotExist:
        return

    if not category.products.exists():
        category.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_add_percent_unit'),
    ]

    operations = [
        migrations.RunPython(seed_precheck_catalog, remove_precheck_catalog),
    ]
