# Generated by Django 4.2.26 on 2025-11-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_seed_precheck_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='precheck',
            name='package_choice',
            field=models.CharField(blank=True, choices=[('', 'Kein Paket ausgewählt'), ('basis', 'Basis-Paket'), ('plus', 'Plus-Paket'), ('pro', 'Pro-Paket')], default='', help_text='Vom Kunden gewünschtes Leistungspaket', max_length=10),
        ),
        migrations.AddField(
            model_name='precheck',
            name='wallbox_pv_surplus',
            field=models.BooleanField(default=False, help_text='PV-Überschussladen für die Wallbox gewünscht'),
        ),
    ]
