# Generated by Django 4.2.26 on 2025-11-11 00:02

from decimal import Decimal

from django.db import migrations


PRODUCT_DEFINITIONS = [
    ("building_efh", "Gebäude Einfamilienhaus", "lump_sum", "Standard ohne Aufschlag", Decimal("0.00")),
    ("building_mfh", "Gebäude Mehrfamilienhaus", "lump_sum", "Zuschlag für Mehrfamilienhaus", Decimal("100.00")),
    ("building_commercial", "Gebäude Gewerbe", "lump_sum", "Zuschlag für Gewerbeobjekt", Decimal("50.00")),
    ("grid_1p", "Hausanschluss 1-polig", "lump_sum", "Aufpreis bei 1-poligem Anschluss", Decimal("100.00")),
    ("grid_3p", "Hausanschluss 3-polig", "lump_sum", "3-polig ohne Aufpreis", Decimal("0.00")),
    ("inverter_tier_3", "Wechselrichter bis 3 kW", "lump_sum", "Kompakter Wechselrichter", Decimal("700.00")),
    ("inverter_tier_5", "Wechselrichter bis 5 kW", "lump_sum", "WR mittelgroß", Decimal("1000.00")),
    ("inverter_tier_10", "Wechselrichter bis 10 kW", "lump_sum", "WR bis 10 kW", Decimal("1500.00")),
    ("inverter_tier_20", "Wechselrichter bis 20 kW", "lump_sum", "WR bis 20 kW", Decimal("2000.00")),
    ("inverter_tier_30", "Wechselrichter bis 30 kW", "lump_sum", "WR bis 30 kW", Decimal("2200.00")),
    ("storage_tier_3", "Speicher bis 3 kWh", "lump_sum", "Kleiner Batteriespeicher", Decimal("1000.00")),
    ("storage_tier_5", "Speicher bis 5 kWh", "lump_sum", "Mittlerer Batteriespeicher", Decimal("1300.00")),
    ("storage_tier_10", "Speicher bis 10 kWh", "lump_sum", "Großer Batteriespeicher", Decimal("2000.00")),
    ("wr_cable_pm_lt10", "Kabelpreis WR <10 kW", "meter", "Preis pro Meter bis 10 kW", Decimal("5.00")),
    ("wr_cable_pm_lt20", "Kabelpreis WR <20 kW", "meter", "Preis pro Meter bis 20 kW", Decimal("15.00")),
    ("wr_cable_pm_lt30", "Kabelpreis WR <30 kW", "meter", "Preis pro Meter bis 30 kW", Decimal("22.00")),
    ("wallbox_cable_pm_lt11", "Wallbox-Kabel <11 kW", "meter", "Preis pro Meter bis 11 kW", Decimal("7.00")),
    ("wallbox_cable_pm_lt20", "Wallbox-Kabel <22 kW", "meter", "Preis pro Meter bis 22 kW", Decimal("14.00")),
    ("wallbox_base_4kw", "Wallbox Installation 4 kW", "lump_sum", "Basisinstallation bis 4 kW", Decimal("300.00")),
    ("wallbox_base_11kw", "Wallbox Installation 11 kW", "lump_sum", "Standardinstallation 11 kW", Decimal("500.00")),
    ("wallbox_base_22kw", "Wallbox Installation 22 kW", "lump_sum", "Schnellladung 22 kW", Decimal("800.00")),
    ("wallbox_mount_stand", "Wallbox Ständermontage", "lump_sum", "Zuschlag für Ständer", Decimal("200.00")),
    ("wallbox_pv_surplus", "PV-Überschussladen", "lump_sum", "Konfiguration Überschussladen", Decimal("200.00")),
    ("package_basis", "Basis-Paket", "package", "Installationspaket Basis", Decimal("890.00")),
    ("package_plus", "Plus-Paket", "package", "Installationspaket Plus", Decimal("1490.00")),
    ("package_pro", "Pro-Paket", "package", "Installationspaket Pro", Decimal("2290.00")),
]


def seed_simple_precheck_prices(apps, schema_editor):
    ProductCategory = apps.get_model('quotes', 'ProductCategory')
    Product = apps.get_model('quotes', 'Product')

    category, _ = ProductCategory.objects.get_or_create(
        name='Precheck',
        defaults={
            'description': 'Preisbausteine für den Precheck-Rechner',
            'sort_order': 50,
            'is_active': True,
        },
    )

    for key, name, unit, description, value in PRODUCT_DEFINITIONS:
        sku = f"PCHK-{key.upper().replace('_', '-')}"
        Product.objects.update_or_create(
            sku=sku,
            defaults={
                'category': category,
                'name': name,
                'description': description,
                'unit': unit,
                'sales_price_net': value,
                'purchase_price_net': Decimal('0.00'),
                'vat_rate': Decimal('0.19'),
                'is_active': True,
                'notes': 'Automatisch verwalteter Precheck-Baustein',
            }
        )


def remove_simple_precheck_prices(apps, schema_editor):
    Product = apps.get_model('quotes', 'Product')
    skus = [f"PCHK-{key.upper().replace('_', '-')}" for key, *_ in PRODUCT_DEFINITIONS]
    Product.objects.filter(sku__in=skus).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_add_precheck_package_fields'),
    ]

    operations = [
        migrations.RunPython(seed_simple_precheck_prices, remove_simple_precheck_prices),
    ]
