# Generated by Django 4.2.26 on 2025-11-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_update_precheck_price_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='precheck',
            name='is_express_package',
            field=models.BooleanField(default=False, help_text='Express-Paket ohne technische Precheck-Details'),
        ),
    ]
