# Generated by Django 4.2.26 on 2025-11-12 02:10

import apps.quotes.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_precheck_is_express_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecheckPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meter_cabinet', 'Zählerschrank'), ('hak', 'Hausanschlusskasten'), ('location', 'Montageorte'), ('cable_route', 'Kabelwege')], max_length=20)),
                ('photo', models.ImageField(help_text='Foto (JPG/PNG, max 5MB)', upload_to='precheck/photos/%Y/%m/', validators=[apps.quotes.validators.validate_image_file])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('precheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quotes.precheck')),
            ],
            options={
                'verbose_name': 'Precheck Foto',
                'verbose_name_plural': 'Precheck Fotos',
                'ordering': ['category', 'uploaded_at'],
            },
        ),
    ]
