# Generated by Django 4.2.26 on 2025-11-12 03:50

import apps.quotes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_precheckphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precheck',
            name='cable_route_photo',
            field=models.FileField(blank=True, help_text='Datei Kabelwege (JPG, PNG oder PDF, max 5MB)', null=True, upload_to='precheck/cables/%Y/%m/', validators=[apps.quotes.validators.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='precheck',
            name='hak_photo',
            field=models.FileField(blank=True, help_text='Datei Hausanschlusskasten (JPG, PNG oder PDF, max 5MB)', null=True, upload_to='precheck/hak/%Y/%m/', validators=[apps.quotes.validators.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='precheck',
            name='location_photo',
            field=models.FileField(blank=True, help_text='Datei Montageorte (JPG, PNG oder PDF, max 5MB)', null=True, upload_to='precheck/locations/%Y/%m/', validators=[apps.quotes.validators.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='precheck',
            name='meter_cabinet_photo',
            field=models.FileField(blank=True, help_text='Datei Zählerschrank (JPG, PNG oder PDF, max 5MB)', null=True, upload_to='precheck/meter_cabinet/%Y/%m/', validators=[apps.quotes.validators.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='precheckphoto',
            name='photo',
            field=models.FileField(help_text='Datei (JPG, PNG oder PDF, max 5MB)', upload_to='precheck/photos/%Y/%m/', validators=[apps.quotes.validators.validate_media_file]),
        ),
    ]
