# Generated by Django 4.2.26 on 2025-11-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0017_alter_precheck_cable_route_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precheck',
            name='backup_power_details',
            field=models.TextField(blank=True, default='', help_text='Details zu Notstrom/Inselbetrieb'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='building_type',
            field=models.CharField(blank=True, choices=[('efh', 'Einfamilienhaus'), ('mfh', 'Mehrfamilienhaus'), ('commercial', 'Gewerbe')], default='', help_text='Gebäudetyp', max_length=20),
        ),
        migrations.AddField(
            model_name='precheck',
            name='construction_year',
            field=models.IntegerField(blank=True, help_text='Baujahr des Gebäudes', null=True),
        ),
        migrations.AddField(
            model_name='precheck',
            name='distance_meter_to_inverter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entfernung Zählerplatz → Wechselrichter in Metern', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='precheck',
            name='feed_in_mode',
            field=models.CharField(blank=True, choices=[('surplus', 'Überschusseinspeisung'), ('full', 'Volleinspeisung'), ('mixed', 'Gemischt')], default='', help_text='Einspeise-Modus', max_length=20),
        ),
        migrations.AddField(
            model_name='precheck',
            name='grid_operator',
            field=models.CharField(blank=True, default='', help_text='Netzbetreiber', max_length=100),
        ),
        migrations.AddField(
            model_name='precheck',
            name='grounding_details',
            field=models.TextField(blank=True, default='', help_text='Details zu Erdung/Potentialausgleich'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='has_deep_earth',
            field=models.CharField(blank=True, choices=[('yes', 'Ja, vorhanden'), ('no', 'Nein'), ('unknown', 'Unbekannt')], default='', help_text='Tiefenerder vorhanden?', max_length=10),
        ),
        migrations.AddField(
            model_name='precheck',
            name='has_grounding',
            field=models.CharField(blank=True, choices=[('yes', 'Ja, vorhanden'), ('no', 'Nein'), ('unknown', 'Unbekannt')], default='', help_text='Erdung/Potentialausgleich vorhanden?', max_length=10),
        ),
        migrations.AddField(
            model_name='precheck',
            name='has_heat_pump',
            field=models.BooleanField(default=False, help_text='Wärmepumpe vorhanden?'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='has_renovation',
            field=models.BooleanField(default=False, help_text='Wurde eine elektrische Sanierung durchgeführt?'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='has_sls_switch',
            field=models.BooleanField(default=False, help_text='SLS-Schalter (Selektiver Hauptleitungsschutzschalter) vorhanden?'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='has_surge_protection_ac',
            field=models.BooleanField(default=False, help_text='Überspannungsschutz AC-Seite vorhanden?'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='has_surge_protection_dc',
            field=models.BooleanField(default=False, help_text='Überspannungsschutz DC-Seite gewünscht?'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='heat_pump_cascade',
            field=models.BooleanField(default=False, help_text='Kaskadenschaltung für Wärmepumpe gewünscht?'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='heat_pump_details',
            field=models.TextField(blank=True, default='', help_text='Details zur Wärmepumpe'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='inverter_location',
            field=models.CharField(blank=True, default='', help_text='Montageort für Wechselrichter', max_length=50),
        ),
        migrations.AddField(
            model_name='precheck',
            name='own_material_description',
            field=models.TextField(blank=True, default='', help_text='Beschreibung der eigenen Komponenten'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='renovation_year',
            field=models.IntegerField(blank=True, help_text='Jahr der letzten elektrischen Sanierung', null=True),
        ),
        migrations.AddField(
            model_name='precheck',
            name='requires_backup_power',
            field=models.BooleanField(default=False, help_text='Inselbetr ieb/Notstrom gewünscht?'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='sls_switch_details',
            field=models.TextField(blank=True, default='', help_text='Details zum SLS-Schalter'),
        ),
        migrations.AddField(
            model_name='precheck',
            name='storage_location',
            field=models.CharField(blank=True, default='', help_text='Montageort für Speicher', max_length=50),
        ),
        migrations.AddField(
            model_name='precheck',
            name='surge_protection_ac_details',
            field=models.TextField(blank=True, default='', help_text='Details zum AC-Überspannungsschutz'),
        ),
    ]
