# Generated by Django 4.2.26 on 2025-11-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_precheck_backup_power_details_precheck_building_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceConfig',
        ),
    ]
