# Generated by Django 4.2.26 on 2025-11-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_remove_priceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precheck',
            name='inverter_location',
            field=models.CharField(blank=True, choices=[('basement', 'Keller'), ('garage', 'Garage'), ('attic', 'Dachboden'), ('utility_room', 'Hauswirtschaftsraum'), ('outdoor', 'Außenbereich (wettergeschützt)'), ('other', 'Anderer Ort')], default='', help_text='Montageort für Wechselrichter', max_length=50),
        ),
        migrations.AlterField(
            model_name='precheck',
            name='storage_location',
            field=models.CharField(blank=True, choices=[('basement', 'Keller'), ('garage', 'Garage'), ('attic', 'Dachboden'), ('utility_room', 'Hauswirtschaftsraum'), ('outdoor', 'Außenbereich (wettergeschützt)'), ('other', 'Anderer Ort')], default='', help_text='Montageort für Speicher', max_length=50),
        ),
    ]
