# Generated by Django 4.2.26 on 2025-11-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_add_location_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precheck',
            name='storage_location',
            field=models.CharField(blank=True, choices=[('same_as_inverter', 'Gleicher Ort wie Wechselrichter'), ('basement', 'Keller'), ('garage', 'Garage'), ('attic', 'Dachboden'), ('utility_room', 'Hauswirtschaftsraum'), ('outdoor', 'Außenbereich (wettergeschützt)'), ('other', 'Anderer Ort')], default='', help_text='Montageort für Speicher', max_length=50),
        ),
    ]
