# Generated by Django 4.2.26 on 2025-11-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_alter_precheck_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Interne Notizen zum Angebot'),
        ),
    ]
