# Generated by Django 4.2.26 on 2025-11-16 00:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_add_quote_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='MwSt.-Satz in Prozent', max_digits=5),
        ),
    ]
