# Generated by Django 4.2.26 on 2025-11-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_add_quoteitem_vat_rate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='precheck',
            index=models.Index(fields=['site', '-created_at'], name='precheck_site_date_idx'),
        ),
        migrations.AddIndex(
            model_name='precheck',
            index=models.Index(fields=['-created_at'], name='precheck_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manufacturer'], name='product_manuf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='product_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='product_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='product_active_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['sort_order', 'is_active'], name='cat_sort_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active', 'name'], name='cat_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', '-created_at'], name='quote_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_by', 'status'], name='quote_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['-created_at'], name='quote_created_idx'),
        ),
    ]
